import React, { useState, useEffect } from 'react';
import {
  ChevronLeft,
  ChevronRight,
  Download,
  Sparkles,
  RefreshCw,
  Play,
  Pause,
  Layers,
  Image as ImageIcon,
  CheckCircle2,
  Share2,
} from 'lucide-react';
import { API_URL } from '../../config.js';

export const VisualStoryViewer = ({
  report,
  onStoryUpdated,
}) => {
  const [currentSlideIndex, setCurrentSlideIndex] = useState(0);
  const [isPlaying, setIsPlaying] = useState(false);
  const [isRegenerating, setIsRegenerating] = useState(false);
  const [selectedFormat, setSelectedFormat] = useState(report.visualStory?.format || 'story');
  const [error, setError] = useState(null);

  const visualStory = report.visualStory;
  const slides = visualStory?.slides || [];
  const currentSlide = slides[currentSlideIndex];

  // Auto-play story slides with timer
  useEffect(() => {
    let interval = null;
    if (isPlaying && slides.length > 1) {
      interval = setInterval(() => {
        setCurrentSlideIndex((prev) => (prev + 1) % slides.length);
      }, 4500);
    }
    return () => clearInterval(interval);
  }, [isPlaying, slides.length]);

  // Keyboard navigation (ArrowLeft, ArrowRight, Space)
  useEffect(() => {
    const handleKeyDown = (e) => {
      if (e.key === 'ArrowRight') {
        setCurrentSlideIndex((prev) => (prev + 1) % slides.length);
      } else if (e.key === 'ArrowLeft') {
        setCurrentSlideIndex((prev) => (prev - 1 + slides.length) % slides.length);
      } else if (e.key === ' ') {
        setIsPlaying((prev) => !prev);
      }
    };
    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, [slides.length]);

  const handleNext = () => {
    setCurrentSlideIndex((prev) => (prev + 1) % slides.length);
  };

  const handlePrev = () => {
    setCurrentSlideIndex((prev) => (prev - 1 + slides.length) % slides.length);
  };

  const handleRegenerate = async (formatToUse = selectedFormat) => {
    setIsRegenerating(true);
    setError(null);
    try {
      const res = await fetch(`${API_URL}/api/reports/${report._id}/visual-story`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ format: formatToUse }),
      });

      if (!res.ok) {
        const data = await res.json();
        throw new Error(data.error || 'Failed to generate visual story');
      }

      const updatedStory = await res.json();
      setCurrentSlideIndex(0);
      if (onStoryUpdated) {
        onStoryUpdated({ ...report, visualStory: updatedStory });
      }
    } catch (err) {
      setError(err.message);
    } finally {
      setIsRegenerating(false);
    }
  };

  const handleDownloadSlide = (slide) => {
    if (!slide?.imageUrl) return;
    const a = document.createElement('a');
    a.href = slide.imageUrl;
    a.target = '_blank';
    a.download = `canopi_story_slide_${slide.order}_${slide.publicId.replace(/\//g, '_')}.jpg`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
  };

  const handleDownloadAll = () => {
    slides.forEach((s, idx) => {
      setTimeout(() => {
        handleDownloadSlide(s);
      }, idx * 300);
    });
  };

  if (!visualStory || slides.length === 0) {
    return (
      <div className="p-8 bg-slate-50 rounded-3xl border border-slate-200/80 text-center space-y-4">
        <div className="w-12 h-12 rounded-2xl bg-cyan-100 text-cyan-700 flex items-center justify-center mx-auto">
          <Sparkles size={24} />
        </div>
        <div>
          <h3 className="text-lg font-bold text-gray-800">No Visual Story Generated Yet</h3>
          <p className="text-xs text-gray-500 max-w-md mx-auto mt-1">
            Turn verified field photos into an Instagram-ready visual story with captions generated by Cloudinary AI Vision.
          </p>
        </div>

        {error && (
          <div className="p-3 bg-red-50 text-red-700 text-xs rounded-xl max-w-md mx-auto">
            {error}
          </div>
        )}

        <div className="flex items-center justify-center space-x-3 pt-2">
          <div className="flex items-center bg-white rounded-xl border border-gray-200 p-1 text-xs">
            <button
              onClick={() => setSelectedFormat('story')}
              className={`px-3 py-1 rounded-lg font-medium transition-all ${
                selectedFormat === 'story'
                  ? 'bg-slate-900 text-white shadow-sm'
                  : 'text-gray-600 hover:text-gray-900'
              }`}
            >
              Story (9:16)
            </button>
            <button
              onClick={() => setSelectedFormat('feed')}
              className={`px-3 py-1 rounded-lg font-medium transition-all ${
                selectedFormat === 'feed'
                  ? 'bg-slate-900 text-white shadow-sm'
                  : 'text-gray-600 hover:text-gray-900'
              }`}
            >
              Feed (4:5)
            </button>
          </div>

          <button
            onClick={() => handleRegenerate(selectedFormat)}
            disabled={isRegenerating}
            className="px-5 py-2 rounded-xl text-xs font-semibold bg-cyan-600 hover:bg-cyan-700 text-white flex items-center space-x-2 transition-all shadow-sm disabled:opacity-50"
          >
            <Sparkles size={14} className={isRegenerating ? 'animate-spin' : ''} />
            <span>{isRegenerating ? 'Analyzing with Cloudinary AI...' : 'Generate Visual Story'}</span>
          </button>
        </div>
      </div>
    );
  }

  return (
    <div className="space-y-4">
      {/* Visual Story Header & Controls Bar */}
      <div className="flex flex-wrap items-center justify-between gap-3 p-4 bg-slate-900 text-white rounded-2xl shadow-sm">
        <div className="flex items-center space-x-3">
          <span className="px-2.5 py-1 bg-cyan-500/20 text-cyan-300 border border-cyan-500/30 text-[10px] font-bold rounded-lg uppercase tracking-wider flex items-center space-x-1">
            <Sparkles size={11} />
            <span>Generated with Cloudinary AI Vision</span>
          </span>
          <h3 className="text-sm font-semibold text-white/90 truncate max-w-md" title={visualStory.title}>
            {visualStory.title}
          </h3>
        </div>

        <div className="flex items-center space-x-2">
          {/* Format Switcher */}
          <div className="flex items-center bg-white/10 p-0.5 rounded-lg text-xs">
            <button
              onClick={() => {
                setSelectedFormat('story');
                if (visualStory.format !== 'story') handleRegenerate('story');
              }}
              className={`px-2 py-0.5 rounded text-[11px] font-medium transition-colors ${
                selectedFormat === 'story' ? 'bg-white text-gray-900 font-bold' : 'text-white/70 hover:text-white'
              }`}
            >
              9:16 Story
            </button>
            <button
              onClick={() => {
                setSelectedFormat('feed');
                if (visualStory.format !== 'feed') handleRegenerate('feed');
              }}
              className={`px-2 py-0.5 rounded text-[11px] font-medium transition-colors ${
                selectedFormat === 'feed' ? 'bg-white text-gray-900 font-bold' : 'text-white/70 hover:text-white'
              }`}
            >
              4:5 Feed
            </button>
          </div>

          {/* Regenerate Button */}
          <button
            onClick={() => handleRegenerate(selectedFormat)}
            disabled={isRegenerating}
            title="Regenerate Visual Story from Latest Verified Evidence"
            className="px-3 py-1 rounded-lg bg-white/10 hover:bg-white/20 text-white text-xs font-medium flex items-center space-x-1 transition-colors disabled:opacity-50"
          >
            <RefreshCw size={12} className={isRegenerating ? 'animate-spin' : ''} />
            <span>{isRegenerating ? 'Regenerating...' : 'Regenerate'}</span>
          </button>

          {/* Download All */}
          <button
            onClick={handleDownloadAll}
            title="Download All Slides"
            className="px-3 py-1 rounded-lg bg-cyan-500 hover:bg-cyan-600 text-white text-xs font-semibold flex items-center space-x-1 transition-colors"
          >
            <Download size={12} />
            <span>Download All</span>
          </button>
        </div>
      </div>

      {error && (
        <div className="p-3 bg-red-50 border border-red-200 text-red-700 text-xs rounded-xl">
          {error}
        </div>
      )}

      {/* Main Instagram Story Style Viewer Canvas */}
      <div className="relative mx-auto max-w-md bg-black rounded-3xl overflow-hidden shadow-2xl border border-gray-800 flex flex-col items-center">
        {/* Story Progress Bars */}
        <div className="absolute top-3 left-3 right-3 z-30 flex space-x-1.5">
          {slides.map((s, idx) => (
            <div
              key={idx}
              onClick={() => setCurrentSlideIndex(idx)}
              className="h-1 flex-1 bg-white/30 rounded-full overflow-hidden cursor-pointer backdrop-blur-sm"
            >
              <div
                className={`h-full transition-all duration-300 ${
                  idx < currentSlideIndex
                    ? 'w-full bg-white'
                    : idx === currentSlideIndex
                    ? 'w-full bg-cyan-400'
                    : 'w-0'
                }`}
              />
            </div>
          ))}
        </div>

        {/* Phase Header Tag */}
        <div className="absolute top-7 left-4 z-30 flex items-center space-x-2">
          <span className="px-2.5 py-0.5 bg-black/60 backdrop-blur-md text-white/90 text-[10px] font-bold rounded-full border border-white/20 uppercase tracking-wider flex items-center space-x-1">
            <CheckCircle2 size={10} className="text-emerald-400" />
            <span>{currentSlide?.phase || `Phase ${currentSlideIndex + 1}`}</span>
          </span>
          <span className="text-[10px] text-white/70 bg-black/40 px-2 py-0.5 rounded-full font-mono">
            {currentSlideIndex + 1}/{slides.length}
          </span>
        </div>

        {/* Story Controls Top Right */}
        <div className="absolute top-7 right-4 z-30 flex items-center space-x-1.5">
          <button
            onClick={() => setIsPlaying((prev) => !prev)}
            title={isPlaying ? 'Pause auto-play' : 'Play story sequence'}
            className="p-1.5 bg-black/60 hover:bg-black/80 backdrop-blur-md text-white rounded-full transition-colors border border-white/20"
          >
            {isPlaying ? <Pause size={12} /> : <Play size={12} />}
          </button>
          <button
            onClick={() => handleDownloadSlide(currentSlide)}
            title="Download this slide"
            className="p-1.5 bg-black/60 hover:bg-black/80 backdrop-blur-md text-white rounded-full transition-colors border border-white/20"
          >
            <Download size={12} />
          </button>
        </div>

        {/* Visual Slide Display */}
        <div className={`w-full ${selectedFormat === 'story' ? 'aspect-[9/16]' : 'aspect-[4/5]'} relative flex items-center justify-center bg-gray-950`}>
          {currentSlide?.imageUrl ? (
            <img
              src={currentSlide.imageUrl}
              alt={currentSlide.caption || 'Visual story slide'}
              className="w-full h-full object-cover select-none animate-in fade-in duration-300"
            />
          ) : (
            <div className="text-gray-500 text-xs flex flex-col items-center">
              <ImageIcon size={32} className="mb-2 opacity-50" />
              <span>Slide image unavailable</span>
            </div>
          )}

          {/* Left / Right Tap / Click navigation zones */}
          <button
            onClick={handlePrev}
            className="absolute left-2 top-1/2 -translate-y-1/2 p-2 rounded-full bg-black/40 hover:bg-black/70 text-white/80 hover:text-white backdrop-blur-sm transition-all z-20"
            title="Previous Slide (or Left Arrow)"
          >
            <ChevronLeft size={20} />
          </button>

          <button
            onClick={handleNext}
            className="absolute right-2 top-1/2 -translate-y-1/2 p-2 rounded-full bg-black/40 hover:bg-black/70 text-white/80 hover:text-white backdrop-blur-sm transition-all z-20"
            title="Next Slide (or Right Arrow)"
          >
            <ChevronRight size={20} />
          </button>
        </div>

        {/* Slide Footer Metadata */}
        <div className="w-full p-3 bg-gray-950 border-t border-gray-800 flex items-center justify-between text-[11px] text-gray-400">
          <span className="truncate max-w-[260px] italic">
            Caption: "{currentSlide?.caption}"
          </span>
          <span className="font-mono text-[10px] text-gray-500 flex-shrink-0">
            {selectedFormat === 'story' ? '1080x1920' : '1080x1350'}
          </span>
        </div>
      </div>
    </div>
  );
};
