import { API_URL } from '../config.js';
import { useState, useEffect } from 'react';
import { CheckCircle, ShieldAlert, FileText, Image as ImageIcon } from 'lucide-react';

export const Evidence = () => {
  const [evidenceList, setEvidenceList] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  useEffect(() => {
    fetch(`${API_URL}/api/evidence`)
      .then(res => res.json())
      .then(data => setEvidenceList(data))
      .catch(err => setError(err.message))
      .finally(() => setLoading(false));
  }, []);

  const handleVerify = async (id) => {
    try {
      const res = await fetch(`${API_URL}/api/evidence/${id}/verify`, { method: 'PUT' });
      if (!res.ok) throw new Error('Failed to verify');
      setEvidenceList(prev => prev.map(ev => 
        ev._id === id ? { ...ev, verified: true } : ev
      ));
    } catch (err) {
      alert(err.message);
    }
  };

  const handleReject = async (id) => {
    try {
      const res = await fetch(`${API_URL}/api/evidence/${id}`, { method: 'DELETE' });
      if (!res.ok) throw new Error('Failed to reject');
      setEvidenceList(prev => prev.filter(ev => ev._id !== id));
    } catch (err) {
      alert(err.message);
    }
  };

  return (
    <div className="max-w-6xl mx-auto space-y-8 animate-in fade-in duration-500">
      <div className="flex items-center justify-between mb-8">
        <div>
          <h1 className="text-3xl font-bold tracking-tight text-gray-800 font-semibold mb-2">Evidence & Verification</h1>
          <p className="text-gray-600">Review and verify AI-generated observations to create trusted impact stories.</p>
        </div>
      </div>

      <div className="space-y-6">
        {loading ? (
          <div className="text-gray-500 py-10 text-center">Loading evidence...</div>
        ) : error ? (
          <div className="text-red-500 py-10 text-center">{error}</div>
        ) : evidenceList.length === 0 ? (
          <div className="text-gray-500 py-10 text-center">No evidence found. Generate some in Comparisons.</div>
        ) : evidenceList.map((evidence) => (
          <div key={evidence._id} className="bw-card-white rounded-3xl p-6 relative overflow-hidden">
            {/* Status Indicator */}
            <div className={`absolute top-0 left-0 w-1 h-full ${evidence.verified ? 'bg-cyan-400' : 'bg-yellow-500/80 shadow-[0_0_15px_rgba(234,179,8,0.5)]'}`}></div>
            
            <div className="flex flex-col md:flex-row justify-between items-start gap-6">
              <div className="space-y-4 flex-1">
                <div className="flex items-center space-x-3">
                  <span className="px-3 py-1 text-xs font-medium bg-white border border-white/50 border border-white/10 rounded-full text-gray-600 uppercase">
                    {evidence.type}
                  </span>
                  <span className="text-xs text-gray-500">{evidence.createdAt}</span>
                </div>
                
                <div>
                  <h3 className="text-xl font-semibold text-slate-700 font-bold mb-2">{evidence.title}</h3>
                  <p className="text-gray-600">{evidence.description}</p>
                </div>
                
                {/* Observations */}
                {evidence.observations && evidence.observations.length > 0 && (
                  <div className="mt-4 bg-white border border-white/50 rounded-3xl p-4 border border-white/5">
                    <h4 className="text-sm font-medium text-gray-800 font-semibold mb-3">AI Observations</h4>
                    <ul className="space-y-3">
                      {evidence.observations.map((obs, idx) => (
                        <li key={idx} className="text-sm text-gray-600">
                          <span className="text-cyan-400 font-medium capitalize">{obs.category}: </span>
                          <span className="text-gray-700">Change identified as </span>
                          <strong className="text-gray-800 font-semibold">{obs.change}</strong>
                        </li>
                      ))}
                    </ul>
                  </div>
                )}
                
                <div className="flex items-center space-x-2 text-xs text-gray-500 pt-2">
                  <FileText size={14} />
                  <span>Generated by {evidence.generatedBy.provider} ({evidence.generatedBy.model})</span>
                </div>
              </div>
              
              <div className="flex flex-col space-y-4 min-w-[200px]">
                {evidence.verified ? (
                  <div className="flex items-center space-x-2 text-cyan-400 bg-cyan-500/10 px-4 py-3 rounded-3xl border border-cyan-500/20">
                    <CheckCircle size={20} />
                    <span className="font-medium">Verified Evidence</span>
                  </div>
                ) : (
                  <div className="space-y-3">
                    <div className="flex items-center space-x-2 text-yellow-500/90 mb-2">
                      <ShieldAlert size={16} />
                      <span className="text-xs font-medium">Pending Human Verification</span>
                    </div>
                    <button 
                      onClick={() => handleVerify(evidence._id)}
                      className="bw-btn-white w-full py-3 rounded-3xl text-gray-800 font-semibold font-medium bg-cyan-600/20 border-cyan-500/30 hover:shadow-[0_0_15px_rgba(34,211,238,0.2)] transition-all"
                    >
                      Verify Claim
                    </button>
                    <button 
                      onClick={() => handleReject(evidence._id)}
                      className="w-full py-3 rounded-3xl text-gray-600 font-medium border border-white/10 hover:bg-white border border-white/50 transition-all"
                    >
                      Reject
                    </button>
                  </div>
                )}
                
                <button className="flex items-center justify-center space-x-2 text-sm text-gray-600 hover:text-gray-800 font-semibold transition-colors py-2">
                  <ImageIcon size={16} />
                  <span>View Source Assets</span>
                </button>
              </div>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
};
